# Generated by Django 3.2.8 on 2021-11-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=250, unique=True)),
                ('slug_category', models.SlugField(max_length=250, unique=True)),
                ('description_cateory', models.TextField(blank=True)),
                ('image_category', models.ImageField(blank=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=250, unique=True)),
                ('slug_product', models.SlugField(max_length=250, unique=True)),
                ('description_product', models.TextField(blank=True)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_product', models.ImageField(blank=True, upload_to='product')),
                ('stock_product', models.IntegerField()),
                ('available_product', models.BooleanField(default=True)),
                ('created_product', models.DateTimeField(auto_now_add=True)),
                ('updated_product', models.DateTimeField(auto_now=True)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
